/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Image, StyleSheet, View } from 'react-native';
import BugBattle from 'react-native-bugbattle-sdk';
import bugbattleLogo from './bugbattleLogo.png';

export default class App extends Component<{}> {
  componentDidMount() {
    BugBattle.initialize("", BugBattle.SHAKE);
  }

  render() {
    return (
      <View style={styles.container}>
        <Image style={styles.logo} source={bugbattleLogo} resizeMode="contain" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#70B9DA',
  },
  logo: {
    width: '65%',
    height: 100
  },
});